from spyne import Application, rpc, ServiceBase, Unicode, Integer, Iterable
from spyne.protocol.soap import Soap11
from spyne.server.wsgi import WsgiApplication
from .xml_processor import XMLProcessor
import logging

logging.basicConfig(level=logging.INFO)

class CTIGatewayService(ServiceBase):
    """
    SOAP Service exposing Cyber Threat Intelligence data.
    The WSDL will be automatically generated by Spyne.
    """
    
    @rpc(_returns=Unicode)
    def GetLatestThreatsXML(ctx):
        """
        Fetches the latest threat intelligence, extracts IoCs, validates against XSD,
        and returns the raw normalized XML string.
        """
        processor = XMLProcessor()
        try:
            normalized_xml = processor.process_feed_to_normalized_xml()
            return normalized_xml.decode('utf-8')
        except Exception as e:
            logging.error(f"Error processing XML: {e}")
            raise Exception(f"Internal Server Error: {e}")

    @rpc(_returns=Unicode)
    def GetThreatDashboardHTML(ctx):
        """
        Fetches the latest threat intelligence and uses XSLT to transform it into an HTML dashboard.
        """
        processor = XMLProcessor()
        try:
            normalized_xml = processor.process_feed_to_normalized_xml()
            html_dashboard = processor.transform_to_html(normalized_xml)
            return html_dashboard.decode('utf-8')
        except Exception as e:
            logging.error(f"Error generating dashboard: {e}")
            raise Exception(f"Internal Server Error: {e}")

# Create the Spyne application with SOAP 1.1 protocol
application = Application([CTIGatewayService],
    tns='http://ctigateway.example.com/soap',
    in_protocol=Soap11(validator='lxml'),
    out_protocol=Soap11()
)

# Wrap it in a WSGI application
wsgi_application = WsgiApplication(application)
